---
ref: b37

aligner: bwamem #tophat hisat bwa bowtie tmap
bam_chr1_base_recal: true
bam_dup_type: markdup
bam_no_filter: false
bam_no_recal: false
bam_no_realn: false
bam_no_sort: false
bam_fix_rg: false
bam_phred64: false
bam_reprocess: false

vcf_post_ann_filter_expression: ExAC_AF > 0.05

# targets_file: intervals.bed
exome: true

# add in facets annotations to vcf
ann_facets: false

# gatk options
gatk_hard_filter_snps: true
gatk_pool_snp_recal: false

# slack_channel: 

qsub_priority: 0
...
