REF = hg18
REF_FASTA = ~/share/references/genomes/hg18.fa
SNP_EFF_GENOME = hg36.54 # == hg18
DBSNP = ~/share/references/dbsnp/dbsnp_132.hg18.vcf
KNOWN_INDELS = ~/share/references/1000g/1000G_biallelic.indels.hg18.vcf
OMNI = ~/share/references/1000g/1000G_omni2.5.hg18.sites.vcf
HAPMAP = ~/share/references/hapmap3/hapmap_3.3.hg18.sites.vcf
GC_WIG = ~/share/references/gc.hg18.wig
MAP_WIG = ~/share/references/map.hg18.wig
