
```{r setup, include=F}
suppressPackageStartupMessages(library("optparse"));
suppressPackageStartupMessages(library("berrylogo"));
suppressPackageStartupMessages(library("ggplot2"));
suppressPackageStartupMessages(library("HapEstXXR"));

if (!interactive()) {
    options(warn = -1, error = quote({ traceback(); q('no', status = 1) }))
}

optList <- list(
                make_option("--lowAF", default = F, action = "store_true", help = "only output low tumor allelic frequency variants"),
                make_option("--highAF", default = F, action = "store_true", help = "only output high tumor allelic frequency variants"))

parser <- OptionParser(usage = "%prog [options]", option_list = optList);
arguments <- parse_args(parser, positional_arguments = T);
opt <- arguments$options;

if (length(args) < 1) {
    cat("Need mutect results table\n");
    print_help(parser);
    stop();
}
mutectFiles <- args

pset <- powerset(1:7)
rnges <- pset[sapply(pset, function(x) length(x) >= 2 & 4 %in% x)]
smallRnges <- rnges[lapply(rnges, length) < 4]
largeRnges <- rnges[lapply(rnges, length) >= 4]

```

# `r opt$name` Mutational Signature Report
---
### Raymond Lim

```{r load_data, include = F}
Data <- list()
for (mutectFile in mutectFiles) {
    sn <- sub('\\..*', '', mutectFile)
    sn <- sub('.*/', '', sn)

    cat("reading", mutectFile, "\n")
    d <- read.table(mutectFile, header=T, as.is = T, sep = '\t');
    d <- subset(d, judgement == "KEEP" & dbsnp_site == "NOVEL")
    if (opt$lowAF) {
        d <- subset(d, tumor_f < 0.15)
    }
    if (opt$highAF) {
        d <- subset(d, tumor_f > 0.15)
    }


    d <- transform(d, mut = paste(ref_allele, alt_allele, sep = ">"))
    Data[[sn]] <- d
}
```

## Mutation berry logos by sample

```{r mut_berrylogos}
allContexts <- list()
for (sn in names(Data)) {
    d <- Data[[sn]]
    splitd <- split(d, d$mut)
    for (mut in names(splitd)) {
        if (nrow(splitd[[mut]]) < 5) {
            next();
        }

        context <- splitd[[mut]]$context
        context <- sub("x", '', context)
        allContexts[[mut]] <- c(allContexts[[mut]], context)
        contextSplit <- t(sapply(context, function(x) unlist(strsplit(x, ''))))
        contextTable <- apply(contextSplit, 2, function(x) table(factor(x, levels = c("A", "T", "C", "G"))))
        pwm <- apply(contextTable, 2, function(x) x / sum(x))

        p <- berrylogo(pwm) + ggtitle(paste(sn, mut))
        print(p)
    }
}
```

## Mutation berry logo for all samples
```{r mut_berrylogos_all}
for (mut in names(allContexts)) {
    contextSplit <- t(sapply(allContexts[[mut]], function(x) unlist(strsplit(x, ''))))
    contextTable <- apply(contextSplit, 2, function(x) table(factor(x, levels = c("A", "T", "C", "G"))))
    pwm <- apply(contextTable, 2, function(x) x / sum(x))
    p <- berrylogo(pwm) + ggtitle(paste('all', mut))
    print(p)
}
```

## Mutation context barplots
```{r small_powerset_barplots, fig.height = 15}
for (sn in names(Data)) {
    d <- Data[[sn]]
    splitd <- split(d, d$mut)
    for (mut in names(splitd)) {
        context <- splitd[[mut]]$context
        contextSplit <- t(sapply(context, function(x) unlist(strsplit(x, ''))))
        for (rnge in smallRnges) {
            rngName <- paste(rnge, collapse = ",")
            tab <- table(as.factor(apply(contextSplit[,rnge], 1, paste, collapse = "")))
            if (any(tab > length(tab) / 3)) {
                barplot(tab, horiz = T, las = 2, main = paste(sn, ' ', mut, ' ', rngName, ' (n = ', sum(tab), ')', sep = ''))
            }
        }
    }
}
```

```{r large_powerset_barplots, fig.height = 35}
for (sn in names(Data)) {
    d <- Data[[sn]]
    splitd <- split(d, d$mut)
    for (mut in names(splitd)) {
        context <- splitd[[mut]]$context
        contextSplit <- t(sapply(context, function(x) unlist(strsplit(x, ''))))
        for (rnge in largeRnges) {
            rngName <- paste(rnge, collapse = ",")
            tab <- table(as.factor(apply(contextSplit[,rnge], 1, paste, collapse = "")))
            if (any(tab > length(tab) / 3)) {
                barplot(tab, horiz = T, las = 2, main = paste(sn, ' ', mut, ' ', rngName, ' (n = ', sum(tab), ')', sep = ''), yaxt = 'n')
                axis(2, cex.axis = 0.8)
            }
        }
    }
}
```
