#!/bin/bash

set -o pipefail

RCMD="Rscript"
NAME="R"
TMPDIR="$HOME/share/tmp"
QUEUE="jrf.q"
LOGDIR=.
MEM="1G"
PARALLEL=1
QSUB="perl modules/scripts/qsub.pl"

while getopts "e:sm:n:l:p:" opt; do
  case $opt in
    l)
    LOGDIR=$OPTARG
      ;;
    e)
    R=$OPTARG
      ;;
    m)
    MEM=$OPTARG
      ;;
    p)
    PARALLEL=$OPTARG
      ;;
    n)
    NAME=$OPTARG
      ;;
    s)
    SGE=true
      ;;
    \:)
      echo "Argument missing: -$OPTARG" >&2
      exit -1
      ;;
    \?)
      echo "Invalid option: -$OPTARG" >&2
      exit -1
      ;;
  esac
done

echo "#---------------------------------";

if [[ $PARALLEL -gt 1 ]]; then
    PE="-pe smp $PARALLEL"
fi

umask 002
mkdir -p $LOGDIR
 
if [[ -n "$R" ]]; then 
    TMP=$(mktemp --tmpdir=${TMPDIR})
    #TMP=$(mktemp -t x)
    trap "{ rm -f ${TMP}; exit 255;  }" SIGINT
    echo "Sys.umask('002')" > ${TMP}
    echo "${R}" >> ${TMP}
    echo "${R}" > $LOGDIR/$NAME.R
    chmod +rx ${TMP}
    source ${HOME}/.bashrc
    if [[ -n "$SGE" ]]; then
        mkdir -p $LOGDIR
        echo "umask 002; ${RCMD} ${TMP}" | $QSUB -- -cwd -V -now n -q $QUEUE -N X$NAME $PE -l virtual_free=$MEM,h_vmem=$MEM -o $LOGDIR/$NAME.log -j y -b n
        RET_CODE=$?
    else
        $RCMD ${TMP} | tee -a $LOGDIR/$NAME.log
        RET_CODE=$?
    fi
    rm -f ${TMP}
    exit ${RET_CODE}
else
    echo "Undefined script" >&2
    exit -1
fi

