```{r setup, include = F}
options(useHTTPS = F)
library("optparse");
library("VariantAnnotation");
library("reshape")
library("boot")
library("plyr")
library("dplyr")
library("ggplot2")
library("RColorBrewer")
library("reshape2")
library("SomaticSignatures")
library("doMC")
library("foreach")
library("NMF")
library("gridExtra")
library("gplots")
library("magrittr")


optList <- list(
                make_option("--name", default = '', type = "character", action = "store", help = "report name"),
                make_option("--ncores", default = 4, type = "integer", action = "store", help = "number of cores"),
                make_option("--alexandrovData", default = '~/share/reference/Alexandrov_NMF_signatures.txt', type = "character", action = "store", help = "alexandrov nmf signatures"),
                make_option("--genome", default = 'b37', help = "reference genome"),
                make_option("--vrangeDir", default = NULL, type = "character", action = "store", help = "input directory"),
                make_option("--outDir", default = NULL, type = "character", action = "store", help = "output directory"),
                make_option("--targetBed", default = NULL, type = "character", action = "store", help = "target intervals in bed format"))

parser <- OptionParser(usage = "%prog [options] [VRange file(s)]", option_list = optList);
arguments <- parse_args(parser, positional_arguments = T, args = args);
opt <- arguments$options;

if (!is.null(opt$vrangeDir)) {
    vrFiles <- list.files(path = opt$vrangeDir,
                          pattern = '.*\\.VRanges\\.Rdata',
                          full.names = T)
}
if (length(arguments$args) > 1) {
    vrFiles <- arguments$args
}
if (length(vrFiles) < 1) {
    cat("Need VRange file(s)\n");
    print_help(parser);
    stop();
}

outFile <- opt$outFile
if (opt$genome == "b37" || opt$genome == "hg19") {
    library("BSgenome.Hsapiens.UCSC.hg19");
    library("TxDb.Hsapiens.UCSC.hg19.knownGene")
    genome <- BSgenome.Hsapiens.UCSC.hg19
    txdb <- TxDb.Hsapiens.UCSC.hg19.knownGene
    genomeName <- 'hg19'
} else if (opt$genome == "mm10" || opt$genome == "GRCm38") {
    library("TxDb.Mmusculus.UCSC.mm10.knownGene")
    library("BSgenome.Mmusculus.UCSC.mm10");
    genome <- BSgenome.Mmusculus.UCSC.mm10
    txdb <- TxDb.Mmusculus.UCSC.mm10.knownGene
    genomeName <- 'mm10'
}

txdb <- renameSeqlevels(txdb, sub('chr', '', seqlevels(txdb)))
txByGenes <- transcriptsBy(txdb, 'gene')
bases <- c("A", "C", "G", "T")

if (!is.null(opt$targetBed)) {
    bed <- ucsc(import(opt$targetBed))
    k3t <- kmerFrequency(genome, 1e5, 3, bed)
    k3wg <- kmerFrequency(genome, 1e5, 3)
    norms <- k3wg[names(k3t)] / k3t
}

registerDoMC(opt$ncores)

theme_set(theme_bw(base_size = 18))
```

# `r opt$name` Mutational Signature Report
---
### Raymond Lim

```{r createMotifMatrices, include = F, cache = F}
vrs <- list()
mm <- list()
mmNorm <- list()
mmTranscribed <- list()
mmUntranscribed <- list()
for (vrFile in vrFiles) {
    s <- sub('\\..*', '', vrFile)
    s <- sub('.*/', '', s)
    load(vrFile)
    vrs[[s]] <- vr
}
vrs <- VRangesList(vrs)
allVr <- unlist(vrs)

mm <- motifMatrix(allVr, normalize = F)
mmNorm <- motifMatrix(allVr, normalize = T)
x <- subset(allVr, allVr$transcribed)
sampleNames(x) <- factor(as.factor(sampleNames(x)))
mmTranscribed <- motifMatrix(x, normalize = T)
x <- subset(allVr, !allVr$transcribed)
sampleNames(x) <- factor(as.factor(sampleNames(x)))
mmUntranscribed <- motifMatrix(x, normalize = T)
if (!is.null(opt$targetBed)) {
    mmNorm <- normalizeMotifs(mmNorm, norms)
    mmTranscribed <- normalizeMotifs(mmTranscribed, norms)
    mmUntranscribed <- normalizeMotifs(mmUntranscribed, norms)
}
```

```{r writeMotifMatrices}
if (!is.null(opt$outDir)) {
    fn <- paste(opt$outDir, "/mm.tsv", sep = "")
    write.table(mm, file = fn, quote = F, sep = '\t')
    fn <- paste(opt$outDir, "/mm_transcribed.tsv", sep = "")
    write.table(mmTranscribed, file = fn, quote = F, sep = '\t')
    fn <- paste(opt$outDir, "/mm_untranscribed.tsv", sep = "")
    write.table(mmUntranscribed, file = fn, quote = F, sep = '\t')
    fn <- paste(opt$outDir, "/mm_norm.tsv", sep = "")
    write.table(mmNorm, file = fn, quote = F, sep = '\t')
}
```

```{r loadAlexandrovData}
alexandrov <- read.table(opt$alexandrovData, sep = '\t', header = T, as.is = T)
rownames(alexandrov) <- paste(sub('>', '', as.character(alexandrov$Substitution.Type)),
                              ' ', subseq(as.character(alexandrov$Trinucleotide), 1, 1), '.',
                              subseq(as.character(alexandrov$Trinucleotide), 3, 3), sep = '')

alexandrovM <- alexandrov[rownames(mm), grepl('Signature', colnames(alexandrov))]

```

```{r nmf, fig.width = 10, fig.height = 10}
solveNMF <- function(x, signatures){
    coef <- fcnnls(x, signatures[rownames(x),, drop = F]) # reorder the rownames of the in matrix 
    colsum <- apply(coef$x, 2, sum)
    coef_x_scaled <- scale(coef$x, center = F, scale = colsum)
    return(coef_x_scaled)
}
nmfCoefs <- solveNMF(as.matrix(alexandrovM), as.matrix(mm))

if (!is.null(opt$outDir)) {
    fn <- paste(opt$outDir, "/nnls_coefs.tsv", sep = "")
    write.table(nmfCoefs, file = fn, quote = F, sep = '\t')
}

cols <- brewer.pal(9, 'Blues')
if (ncol(nmfCoefs) > 2) {
    heatmap.2(nmfCoefs, trace = 'none', margins = c(13, 8), cexCol = 0.8, col = cols, Rowv = F, Colv = F, dendrogram = 'none')
}

par(mar = c(10,5,5,5))
for (s in colnames(nmfCoefs)) {
    barplot(nmfCoefs[,s], main = s, las = 2)
}
```


```{r pie, eval = F, echo = F}
for (s in names(vrs)) {
    vr <- vrs[[s]]
    cols <- c("C>A" = "lightblue", "C>G" = "black", "C>T" = "red", "T>A" = "grey", "T>C" = "lightgreen",  "T>G" = "pink")
    main <- paste(s, " (n = ", length(vr), ")", sep = '')
    pie(table(vr$alteration), col = cols, main = main)
    if (sum(vr$transcribed, na.rm = T) > 0 && sum(!vr$transcribed, na.rm = T) > 0) {
        main <- paste('transcribed', s, " (n=", sum(vr$transcribed, na.rm = T), ")", sep = '')
        pie(table(subset(vr, vr$transcribed)$alteration), col = cols, main = main)
        main <- paste('untranscribed', s, " (n=", sum(!info(vcf)$transcribed, na.rm = T), ")", sep = '')
        pie(table(subset(vr, !vr$transcribed)$alteration), col = cols, main = paste('untranscribed', main))
    }
}
```


```{r mutCountPlots, fig.height = 7, fig.width = 28}
plotMutBarplot <- function(samp, mm) {
    cols <- c("C>A" = "lightblue", "C>G" = "black", "C>T" = "red", "T>A" = "grey", "T>C" = "lightgreen",  "T>G" = "pink")
    mdf <- melt(mm, varnames = c('motif', 'sample'))
    mdf$alteration = sub("([ACGTN])([ACGTN]) .+", "\\1>\\2",
                          mdf$motif)
    mdf$context = sub("[ACGTN][ACGTN] (.+)", "\\1", mdf$motif)
    tit <- paste(samp, ' (n = ', sum(mdf %>% filter(sample == samp) %$% value, na.rm = T), ")", sep = '')
    mdf %>% filter(sample == samp) %>%
        ggplot(aes(x = context, y = value, fill = alteration)) +
        geom_bar(stat = 'identity') +
        facet_grid(~ alteration, switch = 'x') +
        xlab("") + ylab("") + ggtitle(tit) +
        theme(axis.text.x = element_text(angle = 90, hjust = 1),
              legend.position = 'none',
              panel.border = element_blank(),
              axis.line.x = element_line(color = 'black', size = 1),
              axis.line.y = element_line(color = 'black', size = 1),
              panel.grid = element_blank(),
              strip.background = element_blank(),
              strip.text.x = element_text(size = 20)) +
        scale_fill_manual(values = cols)
}

plotMutBarplotStranded <- function(samp, mmTranscribed, mmUntranscribed) {
    mdfTranscribed <- melt(mmTranscribed, varnames = c('motif', 'sample'))
    mdfTranscribed$transcribed <- T
    mdfUntranscribed <- melt(mmUntranscribed, varnames = c('motif', 'sample'))
    mdfUntranscribed$transcribed <- F
    mdf <- rbind(mdfTranscribed, mdfUntranscribed)
    mdf$alteration = sub("([ACGTN])([ACGTN]) .+", "\\1>\\2",
                          mdf$motif)
    mdf$context = sub("[ACGTN][ACGTN] (.+)", "\\1", mdf$motif)
    tit <- paste(samp, ' (n = ', sum(mdf %>% filter(sample == samp) %$% value, na.rm = T), ")", sep = '')
    mdf %>% filter(sample == samp) %>%
        ggplot(aes(x = context, y = value, fill = transcribed)) +
        geom_bar(stat = 'identity', position = 'dodge') +
        facet_grid(~ alteration, switch = 'x') +
        theme(axis.text.x = element_text(angle = 90, hjust = 1),
              panel.border = element_blank(),
              axis.line.x = element_line(color = 'black', size = 1),
              axis.line.y = element_line(color = 'black', size = 1),
              panel.grid = element_blank(),
              strip.background = element_blank(),
              strip.text.x = element_text(size = 20)) +
        scale_fill_manual(name = "", values = c('blue', 'red'),
                          labels = c("Transcribed strand",
                                     'Untranscribed strand')) + 
        xlab("") + ylab("") + ggtitle(tit)
}

plotMutPiechart <- function(samp, mm) {
    mdf <- melt(mm, varnames = c('motif', 'sample'))
    mdf$alteration = sub("([ACGTN])([ACGTN]) .+", "\\1>\\2",
                          mdf$motif)
    mdf$context = sub("[ACGTN][ACGTN] (.+)", "\\1", mdf$motif)
    cols <- c("C>A" = "lightblue", "C>G" = "black", "C>T" = "red", "T>A" = "grey", "T>C" = "lightgreen",  "T>G" = "pink")
    mdf %>% filter(sample == samp) %>% group_by(alteration) %>% summarise(value = sum(value)) %>%
        ggplot(aes(x = "", y = value, fill = alteration)) +
        geom_bar(width = 1, stat = 'identity') + scale_fill_manual(values = cols) + 
        coord_polar("y") + xlab("") + ylab("")
}

for (s in colnames(mm)) {
    p1 <- plotMutBarplot(s, mm)
    p2 <- plotMutPiechart(s, mm)
    grid.arrange(p1, p2, ncol = 2, widths = c(4, 2))

    p1 <- plotMutBarplot(s, mmNorm)
    p2 <- plotMutPiechart(s, mmNorm)
    grid.arrange(p1, p2, ncol = 2, widths = c(4, 2))
}

for (s in colnames(mm)) {
    vr <- vrs[[s]]
    if (sum(vr$transcribed, na.rm = T) > 0 && sum(!vr$transcribed, na.rm = T) > 0) {
        p1 <- plotMutBarplotStranded(s, mmTranscribed, mmUntranscribed)
        p2 <- plotMutPiechart(s, mmTranscribed)
        p3 <- plotMutPiechart(s, mmUntranscribed)
        lom <- matrix(c(1,1, 2,3), nrow = 2, ncol = 2)
        grid.arrange(p1, p2, p3, layout_matrix = lom,  widths = c(4, 2))
    }
}

```


```{r bootPlot, fig.width = 12}
bootFun <- function(x) {
    baseMotif = subseq(as.character(x$motif), 4, 6)
    subseq(baseMotif, 2, 2) = subseq(as.character(x$motif), 1, 1)
    if (!is.null(opt$targetBed)) {
        nval <- x$value * norms[baseMotif]
    } else {
        nval <- x$value
    }
    nval <- nval / sum(nval)
    apply(alexandrovM, 2, function(y) fcnnls(nval, y)$x)
}

ranFun <- function(p, d) {
    # create a vector of same # of mutations using original context probabilities
    s <- sample.int(nrow(p), size = sum(p$value), replace = T, prob = p$value / sum(p$value))
    pp <- p
    tab <- table(p[s, "motif"])
    pp[match(names(tab), pp$motif), "value"] <- tab
    pp
}

mm <- motifMatrix(allVr, normalize = F)
bootDf <- foreach(s = colnames(mm), .combine = 'rbind', .errorhandling = 'remove') %dopar% {
    mdf <- melt(mm[, s, drop = F], varnames = c('motif', 'sample'))
    mdf$alteration = sub("([ACGTN])([ACGTN]) .+", "\\1>\\2",
                          mdf$motif)
    mdf$context = sub("[ACGTN][ACGTN] (.+)", "\\1", mdf$motif)
    boots <- boot(mdf, bootFun, R = 1000, ran.gen = ranFun, sim = 'parametric', parallel = 'multicore')
    boots.sd <- apply(boots$t, 2, sd)
    ci <- norm.ci(boots, index = 1:ncol(alexandrovM))
    Df <- as.data.frame(boots$t0, row.names = 1:ncol(alexandrovM))
    colnames(Df) <- 'bootCor'
    Df$signature <- sub('Signature.', '', colnames(alexandrovM))
    Df$bootSD <- boots.sd
    Df$lowerCI95 <- ci[,2]
    Df$upperCI95 <- ci[,3]
    n <- colnames(alexandrovM)
    Df$votes <- table(factor(n[apply(boots$t, 1, which.max)], levels = n))
    Df$sample <- s
    Df$nCalls <- sum(mm[, s])
    Df$significant <- ! with(Df, bootCor > lowerCI95 & bootCor < upperCI95)
    Df$rank = rank(-Df$votes, ties.method = 'max')
    Df
}

fn <- paste(opt$outDir, "/vote_results.tsv", sep = "")
write.table(bootDf, row.names = F, quote = F, sep = '\t', file = fn)

maxBootDf <- bootDf %>% group_by(sample) %>% filter(votes == max(votes))
fn <- paste(opt$outDir, "/max_vote_results.tsv", sep = "")
write.table(maxBootDf, row.names = F, quote = F, sep = '\t', file = fn)

for (s in colnames(mm)) {
    bdf <- filter(bootDf, sample == s)
    cols <- ifelse(bdf$signficant, 'red', 'grey')
    n <- sub('Signature.', '', colnames(alexandrovM))
    par(mfrow = c(2,1), mar = c(3,5,3,3))
    barCenters <- barplot(bdf$bootCor, ylim = c(min(bdf$bootCor - bdf$bootSD), max(bdf$bootCor + bdf$bootSD)), names.arg = n, col = cols,
                          main = s, ylab = 'Correlation')
    segments(barCenters, bdf$bootCor - bdf$bootSD, barCenters, bdf$bootCor + bdf$bootSD, lwd = 1)
    # vote barplot
    barplot(bdf$votes, ylab = '# Votes', names.arg = bdf$signature)
}
```

